
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: May  6 2022 17:49:29 +07 (May  6 2022 10:49:29 UTC)

// Verification Directory fv/bound_flasher_module 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module bound_flasher_module(clk, rst_n, flick, lamp);
  input clk, rst_n, flick;
  output [16:0] lamp;
  wire clk, rst_n, flick;
  wire [16:0] lamp;
  wire [3:0] F_present_state;
  wire [4:0] a_present_state;
  wire n_0, n_1, n_5, n_6, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_42, n_43, n_44, n_45;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_63, n_64;
  wire n_65, n_66, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_133, n_134, n_135;
  wire n_136, n_137, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_152, n_159, n_163;
  wire n_164, n_165, n_166, n_167, n_169, n_171, n_172, n_175;
  wire n_176, n_177, n_178, n_179, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_194, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_211, n_212, n_213, n_214, n_227;
  wire n_228, n_230, n_231, n_235, n_236, n_237, n_241, n_244;
  wire n_247, n_248, n_254, n_262, n_264, n_268, n_271, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_282, n_2260_BAR, rc_gclk;
  assign lamp[16] = 1'b0;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_209), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  CLKINVX4 g4480(.A (lamp[10]), .Y (n_194));
  INVX1 g4477(.A (n_211), .Y (lamp[5]));
  OAI211X4 g4858__2398(.A0 (flick), .A1 (n_188), .B0 (n_175), .C0
       (n_189), .Y (n_237));
  OA21X2 g4859__5107(.A0 (n_208), .A1 (n_185), .B0 (n_187), .Y (n_189));
  OA21XL g4860__6260(.A0 (F_present_state[0]), .A1 (lamp[10]), .B0
       (n_198), .Y (n_188));
  NOR2X2 g4861__4319(.A (n_184), .B (n_186), .Y (n_187));
  NOR2X2 g4863__8428(.A (n_236), .B (n_211), .Y (n_186));
  OA21X1 g4867__6783(.A0 (F_present_state[3]), .A1 (n_230), .B0
       (lamp[0]), .Y (n_185));
  OR2X6 g4869__3680(.A (n_179), .B (n_13), .Y (n_211));
  NOR2BX4 g4870__1617(.AN (n_231), .B (n_179), .Y (lamp[7]));
  NAND2X1 g4874__2802(.A (n_204), .B (n_183), .Y (lamp[4]));
  OAI21XL g4877__5122(.A0 (n_214), .A1 (n_227), .B0 (n_213), .Y
       (lamp[14]));
  OAI21XL g4878__8246(.A0 (n_247), .A1 (n_227), .B0 (n_213), .Y
       (lamp[13]));
  OAI21XL g4879__7098(.A0 (n_264), .A1 (n_227), .B0 (n_213), .Y
       (lamp[12]));
  NOR2X2 g4880__6131(.A (n_171), .B (n_178), .Y (n_183));
  OR2X1 g4883__1881(.A (n_201), .B (n_178), .Y (lamp[1]));
  NOR2BX2 g4885__7482(.AN (n_228), .B (n_178), .Y (n_182));
  NOR2X4 g4886__4733(.A (n_11), .B (n_178), .Y (n_181));
  AOI21X4 g4887__6161(.A0 (n_244), .A1 (n_172), .B0 (n_179), .Y
       (lamp[0]));
  INVX6 g4888(.A (n_178), .Y (n_213));
  OR2X2 g4889__9315(.A (F_present_state[2]), .B (n_203), .Y (n_235));
  NOR2X6 g4890__9945(.A (n_244), .B (n_172), .Y (n_179));
  AND3X6 g4891__2883(.A (n_241), .B (n_165), .C (n_167), .Y (n_178));
  NAND2BXL g4896__1666(.AN (n_199), .B (flick), .Y (n_175));
  OR2X2 g4899__6417(.A (n_35), .B (n_207), .Y (n_236));
  NAND2BX2 g4900__5477(.AN (F_present_state[1]), .B (n_169), .Y
       (n_203));
  NAND2X6 g4901__2398(.A (n_5), .B (n_152), .Y (n_227));
  NOR3X2 g4903__5107(.A (n_159), .B (n_241), .C (n_264), .Y (n_171));
  NAND2X4 g4904__6260(.A (n_159), .B (n_166), .Y (n_197));
  OR2X6 g4905__4319(.A (n_241), .B (n_167), .Y (n_228));
  NOR2X4 g4906__8428(.A (n_164), .B (n_231), .Y (n_13));
  CLKAND2X6 g4907__5526(.A (n_167), .B (n_165), .Y (n_172));
  OR2X6 g4908__6783(.A (n_241), .B (n_166), .Y (n_200));
  OR2X6 g4914__1617(.A (a_present_state[3]), .B (a_present_state[4]),
       .Y (n_231));
  NOR2X4 g4915__2802(.A (F_present_state[3]), .B (F_present_state[2]),
       .Y (n_38));
  NOR2X4 g4916__1705(.A (n_6), .B (F_present_state[0]), .Y (n_169));
  NOR2X8 g4917__5122(.A (n_241), .B (n_271), .Y (n_152));
  NOR2X4 g4920__8246(.A (n_159), .B (n_247), .Y (n_164));
  NOR2X6 g4924__7098(.A (a_present_state[3]), .B (a_present_state[2]),
       .Y (n_167));
  NAND2X6 g4925__6131(.A (a_present_state[1]), .B (a_present_state[0]),
       .Y (n_166));
  NOR2X8 g4926__1881(.A (a_present_state[0]), .B (a_present_state[1]),
       .Y (n_165));
  CLKINVX4 g4932(.A (a_present_state[2]), .Y (n_159));
  OR2X1 g4951__7482(.A (a_present_state[1]), .B (a_present_state[2]),
       .Y (n_205));
  NAND2X4 g4955__4733(.A (F_present_state[2]), .B (F_present_state[0]),
       .Y (n_208));
  NOR2XL g4957__6161(.A (n_248), .B (n_268), .Y (n_2260_BAR));
  INVX2 g4963(.A (n_227), .Y (n_11));
  INVX1 g4967(.A (n_182), .Y (lamp[3]));
  INVX1 g4969(.A (n_13), .Y (n_230));
  INVXL g4971(.A (n_183), .Y (n_202));
  NAND2X4 g4975__9945(.A (n_163), .B (n_228), .Y (n_201));
  INVX1 g4977(.A (n_181), .Y (lamp[11]));
  NAND2X2 g4987__1666(.A (n_254), .B (n_182), .Y (lamp[2]));
  INVX2 g4989(.A (lamp[0]), .Y (n_212));
  DFFRHQX8 \F_present_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_145),
       .Q (F_present_state[0]));
  DFFRHQX4 \F_present_state_reg[1] (.RN (rst_n), .CK (rc_gclk), .D
       (n_144), .Q (F_present_state[1]));
  DFFRHQX8 \F_present_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_139),
       .Q (F_present_state[2]));
  DFFRHQX8 \F_present_state_reg[3] (.RN (rst_n), .CK (rc_gclk), .D
       (n_147), .Q (F_present_state[3]));
  DFFRHQX8 \a_present_state_reg[0] (.RN (rst_n), .CK (rc_gclk), .D
       (n_149), .Q (a_present_state[0]));
  DFFRHQX8 \a_present_state_reg[1] (.RN (rst_n), .CK (rc_gclk), .D
       (n_143), .Q (a_present_state[1]));
  DFFRHQX4 \a_present_state_reg[2] (.RN (rst_n), .CK (rc_gclk), .D
       (n_148), .Q (a_present_state[2]));
  DFFRHQX4 \a_present_state_reg[3] (.RN (rst_n), .CK (rc_gclk), .D
       (n_146), .Q (a_present_state[3]));
  DFFRHQX4 \a_present_state_reg[4] (.RN (rst_n), .CK (rc_gclk), .D
       (n_108), .Q (a_present_state[4]));
  OAI221X2 g6635__7410(.A0 (a_present_state[0]), .A1 (n_119), .B0
       (n_231), .B1 (n_136), .C0 (n_137), .Y (n_149));
  OR3X1 g6636__6417(.A (n_134), .B (n_142), .C (n_141), .Y (n_148));
  OAI22X2 g6639__5477(.A0 (n_212), .A1 (n_278), .B0 (n_94), .B1
       (n_109), .Y (n_147));
  OAI32X1 g6644__2398(.A0 (n_117), .A1 (n_56), .A2 (n_275), .B0 (n_0),
       .B1 (n_237), .Y (n_145));
  OAI22X2 g6645__5107(.A0 (n_0), .A1 (n_131), .B0 (n_24), .B1 (n_92),
       .Y (n_144));
  AOI21X1 g6647__6260(.A0 (n_106), .A1 (n_124), .B0 (n_44), .Y (n_142));
  AOI211X2 g6648__4319(.A0 (n_35), .A1 (n_123), .B0 (n_122), .C0
       (n_116), .Y (n_141));
  OR4X1 g6649__8428(.A (n_0), .B (n_114), .C (n_91), .D (n_126), .Y
       (n_140));
  OAI221X2 g6651__5526(.A0 (n_0), .A1 (n_93), .B0 (n_53), .B1 (n_203),
       .C0 (n_133), .Y (n_139));
  NOR2X1 g6653__3680(.A (n_127), .B (n_130), .Y (n_137));
  OA21X1 g6654__1617(.A0 (n_262), .A1 (n_236), .B0 (n_129), .Y (n_136));
  AOI21X1 g6655__2802(.A0 (n_82), .A1 (n_102), .B0 (n_125), .Y (n_135));
  OAI22X1 g6656__1705(.A0 (n_203), .A1 (n_115), .B0 (n_19), .B1
       (n_100), .Y (n_134));
  NAND3BX2 g6657__5122(.AN (n_24), .B (n_79), .C (n_121), .Y (n_133));
  OAI2BB1X1 g6660__8246(.A0N (n_66), .A1N (n_101), .B0 (n_282), .Y
       (n_130));
  OAI211X1 g6661__7098(.A0 (n_77), .A1 (n_102), .B0 (n_1), .C0 (n_205),
       .Y (n_129));
  AOI222X2 g6662__6131(.A0 (n_29), .A1 (n_30), .B0 (n_230), .B1 (n_40),
       .C0 (n_99), .C1 (n_101), .Y (n_128));
  OA22XL g6663__1881(.A0 (n_30), .A1 (n_101), .B0 (n_1), .B1
       (n_2260_BAR), .Y (n_127));
  OAI21X1 g6664__5115(.A0 (n_16), .A1 (lamp[8]), .B0 (n_112), .Y
       (n_126));
  OAI21X1 g6665__7482(.A0 (n_28), .A1 (n_97), .B0 (n_113), .Y (n_125));
  AOI221X2 g6666__4733(.A0 (n_38), .A1 (n_68), .B0 (n_47), .B1 (n_64),
       .C0 (n_103), .Y (n_124));
  OAI21X1 g6667__6161(.A0 (n_207), .A1 (n_103), .B0 (n_42), .Y (n_123));
  AOI2BB1XL g6668__9315(.A0N (F_present_state[3]), .A1N (n_100), .B0
       (n_208), .Y (n_122));
  OAI21X2 g6669__9945(.A0 (n_63), .A1 (n_31), .B0 (n_107), .Y (n_121));
  NAND2X2 g6670__2883(.A (n_33), .B (n_73), .Y (n_120));
  AOI221X1 g6671__2346(.A0 (n_43), .A1 (n_77), .B0 (n_48), .B1 (n_40),
       .C0 (n_55), .Y (n_119));
  NAND2X1 g6673__7410(.A (n_32), .B (n_89), .Y (n_117));
  OAI21X1 g6674__6417(.A0 (n_206), .A1 (n_84), .B0 (n_105), .Y (n_116));
  MXI2X1 g6675__5477(.A (n_86), .B (n_64), .S0 (F_present_state[2]), .Y
       (n_115));
  AOI21X1 g6676__2398(.A0 (n_35), .A1 (n_86), .B0 (F_present_state[2]),
       .Y (n_114));
  AOI32X2 g6677__5107(.A0 (F_present_state[2]), .A1 (n_0), .A2 (n_17),
       .B0 (n_26), .B1 (n_85), .Y (n_113));
  AOI21XL g6683__5526(.A0 (n_58), .A1 (flick), .B0
       (F_present_state[3]), .Y (n_109));
  NOR2XL g6684__6783(.A (n_86), .B (n_235), .Y (n_108));
  OAI21X1 g6687__3680(.A0 (n_202), .A1 (n_277), .B0 (n_14), .Y (n_106));
  OA21XL g6688__1617(.A0 (n_68), .A1 (n_236), .B0 (F_present_state[1]),
       .Y (n_105));
  OAI21X2 g6689__2802(.A0 (n_69), .A1 (n_27), .B0 (n_83), .Y (n_104));
  OAI21X1 g6690__1705(.A0 (n_214), .A1 (n_66), .B0 (n_25), .Y (n_99));
  NOR3X1 g6693__8246(.A (n_60), .B (n_277), .C (n_80), .Y (n_97));
  NOR2X2 g6694__7098(.A (n_96), .B (n_45), .Y (n_103));
  AOI21X4 g6695__6131(.A0 (F_present_state[1]), .A1 (n_198), .B0
       (n_81), .Y (n_102));
  AOI211X2 g6696__1881(.A0 (n_35), .A1 (n_42), .B0
       (F_present_state[1]), .C0 (n_22), .Y (n_101));
  NAND2X2 g6697__5115(.A (n_95), .B (n_276), .Y (n_100));
  ADDHX1 g6698__7482(.A (n_248), .B (n_1), .CO (n_95), .S (n_96));
  AOI22X1 g6700__6161(.A0 (n_12), .A1 (n_21), .B0 (n_39), .B1 (n_20),
       .Y (n_93));
  AOI211XL g6701__9315(.A0 (F_present_state[2]), .A1 (n_194), .B0
       (n_50), .C0 (n_211), .Y (n_92));
  AND2X1 g6702__9945(.A (n_64), .B (n_76), .Y (n_91));
  AOI2BB1X1 g6705__2346(.A0N (n_18), .A1N (n_212), .B0 (n_24), .Y
       (n_89));
  NAND2X1 g6706__1666(.A (n_65), .B (n_198), .Y (n_88));
  OAI211X2 g6708__7410(.A0 (n_262), .A1 (n_228), .B0 (n_254), .C0
       (n_213), .Y (n_85));
  MX2XL g6709__6417(.A (n_43), .B (n_276), .S0 (n_262), .Y (n_84));
  AO21XL g6711__2398(.A0 (n_10), .A1 (n_48), .B0 (n_80), .Y (n_82));
  NAND3X2 g6714__6260(.A (n_51), .B (n_47), .C (n_44), .Y (n_87));
  CLKMX2X3 g6715__4319(.A (n_43), .B (n_11), .S0 (n_214), .Y (n_86));
  OAI21XL g6717__8428(.A0 (n_9), .A1 (n_206), .B0 (n_50), .Y (n_76));
  NOR3XL g6718__5526(.A (F_present_state[0]), .B (n_0), .C (n_38), .Y
       (n_75));
  OAI22X1 g6719__6783(.A0 (n_207), .A1 (flick), .B0 (n_35), .B1 (n_37),
       .Y (n_74));
  OAI21X1 g6720__3680(.A0 (n_13), .A1 (n_36), .B0 (n_17), .Y (n_73));
  NOR3XL g6721__1617(.A (F_present_state[3]), .B (n_8), .C (n_208), .Y
       (n_72));
  NOR2XL g6723__1705(.A (n_40), .B (n_55), .Y (n_70));
  NOR2X1 g6725__5122(.A (n_262), .B (n_45), .Y (n_80));
  AOI21X2 g6726__8246(.A0 (n_38), .A1 (n_211), .B0 (n_49), .Y (n_79));
  NOR2X2 g6727__7098(.A (flick), .B (n_56), .Y (n_78));
  NOR2X2 g6728__6131(.A (n_52), .B (n_206), .Y (n_77));
  MX2XL g6734__5115(.A (n_214), .B (n_262), .S0 (n_268), .Y (n_61));
  OAI22X1 g6736__7482(.A0 (n_5), .A1 (n_200), .B0 (n_214), .B1 (n_231),
       .Y (n_60));
  AOI21XL g6737__4733(.A0 (n_268), .A1 (n_205), .B0 (n_228), .Y (n_59));
  AO21XL g6738__6161(.A0 (n_268), .A1 (n_197), .B0 (n_241), .Y (n_58));
  OR2X2 g6739__9315(.A (n_42), .B (n_44), .Y (n_69));
  NAND2X2 g6740__9945(.A (n_214), .B (n_48), .Y (n_68));
  AO21X1 g6742__2346(.A0 (n_5), .A1 (n_268), .B0 (n_228), .Y (n_66));
  NAND2X2 g6744__7410(.A (n_262), .B (n_43), .Y (n_64));
  NOR2X2 g6745__6417(.A (F_present_state[2]), .B (n_16), .Y (n_63));
  NOR2XL g6748__2398(.A (F_present_state[2]), .B (lamp[15]), .Y (n_53));
  NAND2X1 g6750__5107(.A (n_9), .B (n_0), .Y (n_52));
  NAND2X1 g6751__6260(.A (F_present_state[1]), .B (n_35), .Y (n_51));
  CLKAND2X2 g6753__4319(.A (n_207), .B (flick), .Y (n_57));
  NOR2X4 g6754__8428(.A (n_208), .B (n_194), .Y (n_56));
  NOR2X1 g6755__5526(.A (n_227), .B (n_235), .Y (n_55));
  NAND2X1 g6760__6783(.A (F_present_state[0]), .B (n_6), .Y (n_50));
  NOR2XL g6761__3680(.A (F_present_state[2]), .B (F_present_state[0]),
       .Y (n_49));
  NOR2X2 g6763__1617(.A (n_5), .B (n_231), .Y (n_48));
  NOR2X4 g6765__2802(.A (F_present_state[3]), .B (n_9), .Y (n_47));
  OR2X4 g6767__5122(.A (F_present_state[1]), .B (n_35), .Y (n_44));
  NOR2X4 g6768__8246(.A (n_5), .B (n_204), .Y (n_43));
  NAND2X4 g6769__7098(.A (F_present_state[3]), .B (F_present_state[2]),
       .Y (n_42));
  CLKINVX4 g6783(.A (F_present_state[0]), .Y (n_35));
  NOR2XL g6789__6131(.A (F_present_state[3]), .B (F_present_state[0]),
       .Y (n_17));
  NAND2X4 g6809__1881(.A (F_present_state[3]), .B (F_present_state[0]),
       .Y (n_16));
  BUFX8 fopt6819(.A (a_present_state[2]), .Y (n_5));
  BUFX6 fopt6840(.A (F_present_state[1]), .Y (n_0));
  INVXL g6843(.A (n_49), .Y (n_18));
  OR2X1 g6845__5115(.A (n_194), .B (n_36), .Y (n_21));
  NAND2XL g6849__7482(.A (F_present_state[2]), .B (n_8), .Y (n_19));
  INVXL g6851(.A (n_42), .Y (n_14));
  INVXL g6853(.A (n_199), .Y (n_12));
  INVX2 g6859(.A (F_present_state[2]), .Y (n_9));
  INVXL g6861(.A (n_214), .Y (n_10));
  INVXL g6865(.A (F_present_state[1]), .Y (n_8));
  INVXL g6867(.A (n_63), .Y (n_23));
  INVX2 g6869(.A (n_65), .Y (n_24));
  NAND2XL g6871__4733(.A (F_present_state[3]), .B (n_212), .Y (n_20));
  NOR2X1 g6873__6161(.A (n_35), .B (n_47), .Y (n_22));
  AOI21X2 g6875__9315(.A0 (n_1), .A1 (n_201), .B0 (lamp[15]), .Y
       (n_27));
  OR2XL g6877__9945(.A (n_61), .B (n_66), .Y (n_29));
  OAI2BB1XL g6881__2883(.A0N (n_23), .A1N (n_199), .B0 (n_211), .Y
       (n_32));
  AOI21X2 g6883__2346(.A0 (n_39), .A1 (n_194), .B0 (n_88), .Y (n_33));
  INVX1 g6885(.A (n_87), .Y (n_30));
  INVX1 g6887(.A (n_77), .Y (n_28));
  INVX1 g6889(.A (n_69), .Y (n_26));
  INVXL g6891(.A (n_277), .Y (n_25));
  NAND2XL g6893__1666(.A (n_100), .B (n_72), .Y (n_34));
  INVX2 fopt6895(.A (F_present_state[3]), .Y (n_6));
  AOI21X2 g6897__7410(.A0 (F_present_state[0]), .A1 (n_57), .B0 (n_78),
       .Y (n_31));
  INVXL g6898(.A (n_211), .Y (n_107));
  OAI2BB1X2 g6900__6417(.A0N (n_17), .A1N (n_21), .B0 (n_279), .Y
       (n_131));
  OAI211X2 g6904__2398(.A0 (n_96), .A1 (n_70), .B0 (n_128), .C0
       (n_135), .Y (n_143));
  OAI211X2 g6906__5107(.A0 (n_64), .A1 (n_28), .B0 (n_34), .C0 (n_140),
       .Y (n_146));
  CLKINVX4 fopt6909(.A (n_241), .Y (n_244));
  BUFX16 fopt6910(.A (a_present_state[4]), .Y (n_241));
  OR2X2 g6921__6260(.A (n_247), .B (n_241), .Y (n_163));
  CLKINVX4 fopt6923(.A (n_264), .Y (n_262));
  BUFX6 fopt6924(.A (n_165), .Y (n_264));
  CLKAND2X3 g2(.A (n_176), .B (lamp[7]), .Y (lamp[10]));
  NOR2BXL g6932(.AN (n_186), .B (flick), .Y (n_275));
  NOR2BX4 g6933(.AN (n_5), .B (n_231), .Y (n_276));
  NOR2BX2 g6934(.AN (n_43), .B (n_262), .Y (n_277));
  OA22X1 g6935(.A0 (n_6), .A1 (n_44), .B0 (n_74), .B1 (n_120), .Y
       (n_278));
  AND3X4 g6936(.A (n_79), .B (n_71), .C (n_280), .Y (n_279));
  OA22X1 g6937(.A0 (n_16), .A1 (n_212), .B0 (n_35), .B1 (n_42), .Y
       (n_280));
  OR2X1 g6931__6939(.A (n_159), .B (n_200), .Y (n_177));
  BUFX2 fopt6941(.A (n_200), .Y (n_254));
  INVX2 g6943(.A (n_169), .Y (n_206));
  NOR2X1 g6712__6945(.A (n_0), .B (n_63), .Y (n_81));
  NAND2XL g6710__6947(.A (F_present_state[1]), .B (n_63), .Y (n_83));
  INVX3 g6949(.A (n_276), .Y (n_45));
  INVX2 g6951(.A (n_213), .Y (lamp[15]));
  AOI21X2 g4875__6953(.A0 (n_9), .A1 (n_178), .B0 (n_206), .Y (n_184));
  INVX1 g6955(.A (n_236), .Y (n_40));
  NAND2BX1 g2__6957(.AN (lamp[7]), .B (n_177), .Y (lamp[6]));
  INVX1 g6959(.A (n_211), .Y (n_37));
  OAI2BB1XL g6699__6961(.A0N (F_present_state[2]), .A1N (n_211), .B0
       (n_75), .Y (n_94));
  AND2XL g6679__6963(.A (n_207), .B (n_100), .Y (n_112));
  BUFX3 g6965(.A (n_166), .Y (n_214));
  NAND2X2 g4961__6967(.A (n_35), .B (n_38), .Y (n_198));
  OR2X1 g4912__6969(.A (F_present_state[0]), .B (n_9), .Y (n_199));
  INVX3 g6971(.A (n_38), .Y (n_207));
  AND2X1 g6743__6973(.A (n_0), .B (n_42), .Y (n_65));
  INVXL g6975(.A (n_208), .Y (n_39));
  INVX2 fopt6977(.A (n_271), .Y (n_268));
  INVX3 fopt6979(.A (n_247), .Y (n_248));
  OAI2BB1XL g6722__6981(.A0N (n_208), .A1N (n_206), .B0 (n_37), .Y
       (n_71));
  INVX3 fopt6983(.A (a_present_state[3]), .Y (n_271));
  INVX3 fopt6985(.A (a_present_state[1]), .Y (n_247));
  INVX2 g6987(.A (flick), .Y (n_36));
  INVX2 fopt6989(.A (a_present_state[0]), .Y (n_1));
  OR2XL g4985__6991(.A (n_235), .B (n_237), .Y (n_209));
  OAI2BB1X2 g6992(.A0N (n_262), .A1N (n_152), .B0 (n_181), .Y
       (lamp[8]));
  AOI2BB1X2 g6993(.A0N (n_59), .A1N (n_87), .B0 (n_104), .Y (n_282));
  OR2X1 g4893__6995(.A (n_241), .B (n_197), .Y (n_176));
  INVX3 fopt6997(.A (n_152), .Y (n_204));
  OAI2BB1XL g4884__6999(.A0N (n_205), .A1N (n_152), .B0 (n_213), .Y
       (lamp[9]));
endmodule

